-- Enhanced Holiday Packages Component Database Schema for Joomla 5
-- This creates all necessary tables for a complete travel booking system

-- Main Destinations Table
CREATE TABLE IF NOT EXISTS `#__hp_destinations` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(255) NOT NULL DEFAULT '',
    `description` text,
    `short_description` varchar(500) DEFAULT '',
    `image` varchar(255) DEFAULT '',
    `gallery` text,
    `country` varchar(100) DEFAULT '',
    `state` varchar(100) DEFAULT '',
    `city` varchar(100) DEFAULT '',
    `latitude` decimal(10,8) DEFAULT NULL,
    `longitude` decimal(11,8) DEFAULT NULL,
    `weather_info` text,
    `best_time_to_visit` varchar(255) DEFAULT '',
    `language_spoken` varchar(255) DEFAULT '',
    `currency` varchar(10) DEFAULT '',
    `timezone` varchar(50) DEFAULT '',
    `popular_attractions` text,
    `meta_title` varchar(255) DEFAULT '',
    `meta_description` varchar(500) DEFAULT '',
    `meta_keywords` varchar(255) DEFAULT '',
    `featured` tinyint(1) DEFAULT 0,
    `published` tinyint(1) DEFAULT 1,
    `ordering` int(11) DEFAULT 0,
    `created_by` int(11) unsigned DEFAULT 0,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified_by` int(11) unsigned DEFAULT 0,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `checked_out` int(11) unsigned DEFAULT 0,
    `checked_out_time` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_alias` (`alias`),
    KEY `idx_published` (`published`),
    KEY `idx_featured` (`featured`),
    KEY `idx_country` (`country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Package Categories Table
CREATE TABLE IF NOT EXISTS `#__hp_categories` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(255) NOT NULL DEFAULT '',
    `description` text,
    `image` varchar(255) DEFAULT '',
    `icon_class` varchar(100) DEFAULT '',
    `color` varchar(7) DEFAULT '#007bff',
    `parent_id` int(11) unsigned DEFAULT 0,
    `level` int(11) unsigned DEFAULT 1,
    `path` varchar(500) DEFAULT '',
    `published` tinyint(1) DEFAULT 1,
    `ordering` int(11) DEFAULT 0,
    `created_by` int(11) unsigned DEFAULT 0,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified_by` int(11) unsigned DEFAULT 0,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_alias` (`alias`),
    KEY `idx_published` (`published`),
    KEY `idx_parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Enhanced Holiday Packages Table
CREATE TABLE IF NOT EXISTS `#__hp_packages` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(255) NOT NULL DEFAULT '',
    `category_id` int(11) unsigned DEFAULT 0,
    `destination_id` int(11) unsigned DEFAULT 0,
    `short_description` varchar(500) DEFAULT '',
    `description` longtext,
    `image` varchar(255) DEFAULT '',
    `gallery` text,
    `duration_days` int(11) DEFAULT 1,
    `duration_nights` int(11) DEFAULT 0,
    `min_age` int(11) DEFAULT 0,
    `max_group_size` int(11) DEFAULT 50,
    `difficulty_level` enum('Easy','Moderate','Challenging','Extreme') DEFAULT 'Easy',
    `package_type` enum('Standard','Premium','Luxury','Budget') DEFAULT 'Standard',
    `travel_style` enum('Adventure','Cultural','Relaxation','Family','Romantic','Business','Wildlife','Religious','Beach','Mountain','Desert','City') DEFAULT 'Cultural',
    `transportation_mode` set('Flight','Train','Bus','Car','Boat','Walking','Bicycle') DEFAULT 'Car',
    `accommodation_type` enum('Hotel','Resort','Hostel','Homestay','Camping','Apartment','Villa','Cruise') DEFAULT 'Hotel',
    `meal_plan` enum('No Meals','Breakfast Only','Half Board','Full Board','All Inclusive') DEFAULT 'Breakfast Only',
    `price_adult` decimal(10,2) DEFAULT 0.00,
    `price_child` decimal(10,2) DEFAULT 0.00,
    `price_infant` decimal(10,2) DEFAULT 0.00,
    `price_senior` decimal(10,2) DEFAULT 0.00,
    `currency` varchar(3) DEFAULT 'USD',
    `discount_percentage` decimal(5,2) DEFAULT 0.00,
    `discount_amount` decimal(10,2) DEFAULT 0.00,
    `early_bird_discount` decimal(5,2) DEFAULT 0.00,
    `group_discount` decimal(5,2) DEFAULT 0.00,
    `seasonal_pricing` text,
    `inclusions` longtext,
    `exclusions` longtext,
    `highlights` longtext,
    `itinerary` longtext,
    `terms_conditions` longtext,
    `cancellation_policy` text,
    `visa_requirements` text,
    `health_requirements` text,
    `packing_list` text,
    `faqs` longtext,
    `availability_calendar` longtext,
    `departure_dates` text,
    `departure_cities` text,
    `booking_deadline` int(11) DEFAULT 7,
    `min_advance_booking` int(11) DEFAULT 1,
    `instant_booking` tinyint(1) DEFAULT 0,
    `free_cancellation_days` int(11) DEFAULT 0,
    `rating` decimal(3,2) DEFAULT 0.00,
    `review_count` int(11) DEFAULT 0,
    `popularity_score` int(11) DEFAULT 0,
    `total_bookings` int(11) DEFAULT 0,
    `tags` text,
    `meta_title` varchar(255) DEFAULT '',
    `meta_description` varchar(500) DEFAULT '',
    `meta_keywords` varchar(255) DEFAULT '',
    `featured` tinyint(1) DEFAULT 0,
    `hot_deal` tinyint(1) DEFAULT 0,
    `trending` tinyint(1) DEFAULT 0,
    `published` tinyint(1) DEFAULT 1,
    `ordering` int(11) DEFAULT 0,
    `created_by` int(11) unsigned DEFAULT 0,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified_by` int(11) unsigned DEFAULT 0,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `publish_up` datetime DEFAULT NULL,
    `publish_down` datetime DEFAULT NULL,
    `checked_out` int(11) unsigned DEFAULT 0,
    `checked_out_time` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_alias` (`alias`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_destination_id` (`destination_id`),
    KEY `idx_published` (`published`),
    KEY `idx_featured` (`featured`),
    KEY `idx_hot_deal` (`hot_deal`),
    KEY `idx_trending` (`trending`),
    KEY `idx_package_type` (`package_type`),
    KEY `idx_travel_style` (`travel_style`),
    KEY `idx_price_adult` (`price_adult`),
    KEY `idx_rating` (`rating`),
    KEY `idx_duration_days` (`duration_days`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Package Itinerary Details Table
CREATE TABLE IF NOT EXISTS `#__hp_itinerary` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `package_id` int(11) unsigned NOT NULL,
    `day_number` int(11) NOT NULL,
    `title` varchar(255) NOT NULL,
    `description` longtext,
    `activities` text,
    `meals` varchar(255) DEFAULT '',
    `accommodation` varchar(255) DEFAULT '',
    `transportation` varchar(255) DEFAULT '',
    `distance_covered` varchar(100) DEFAULT '',
    `travel_time` varchar(100) DEFAULT '',
    `altitude` varchar(100) DEFAULT '',
    `weather_note` text,
    `important_notes` text,
    `images` text,
    `optional_activities` text,
    `free_time` text,
    `wake_up_time` time DEFAULT NULL,
    `departure_time` time DEFAULT NULL,
    `arrival_time` time DEFAULT NULL,
    `ordering` int(11) DEFAULT 0,
    `published` tinyint(1) DEFAULT 1,
    PRIMARY KEY (`id`),
    KEY `idx_package_id` (`package_id`),
    KEY `idx_day_number` (`day_number`),
    FOREIGN KEY (`package_id`) REFERENCES `#__hp_packages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Customers Table
CREATE TABLE IF NOT EXISTS `#__hp_customers` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `user_id` int(11) unsigned DEFAULT 0,
    `first_name` varchar(100) NOT NULL,
    `last_name` varchar(100) NOT NULL,
    `email` varchar(255) NOT NULL,
    `phone` varchar(20) DEFAULT '',
    `mobile` varchar(20) DEFAULT '',
    `date_of_birth` date DEFAULT NULL,
    `gender` enum('Male','Female','Other') DEFAULT NULL,
    `nationality` varchar(100) DEFAULT '',
    `passport_number` varchar(50) DEFAULT '',
    `passport_expiry` date DEFAULT NULL,
    `address_line1` varchar(255) DEFAULT '',
    `address_line2` varchar(255) DEFAULT '',
    `city` varchar(100) DEFAULT '',
    `state` varchar(100) DEFAULT '',
    `country` varchar(100) DEFAULT '',
    `postal_code` varchar(20) DEFAULT '',
    `emergency_contact_name` varchar(255) DEFAULT '',
    `emergency_contact_phone` varchar(20) DEFAULT '',
    `emergency_contact_relation` varchar(100) DEFAULT '',
    `dietary_requirements` text,
    `medical_conditions` text,
    `travel_insurance` tinyint(1) DEFAULT 0,
    `newsletter_subscription` tinyint(1) DEFAULT 1,
    `marketing_consent` tinyint(1) DEFAULT 0,
    `loyalty_points` int(11) DEFAULT 0,
    `customer_type` enum('Regular','VIP','Corporate') DEFAULT 'Regular',
    `registration_source` varchar(100) DEFAULT 'Website',
    `notes` text,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `last_login` datetime DEFAULT NULL,
    `active` tinyint(1) DEFAULT 1,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_email` (`email`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_customer_type` (`customer_type`),
    KEY `idx_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Bookings Table
CREATE TABLE IF NOT EXISTS `#__hp_bookings` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `booking_reference` varchar(20) NOT NULL,
    `customer_id` int(11) unsigned NOT NULL,
    `package_id` int(11) unsigned NOT NULL,
    `departure_date` date NOT NULL,
    `return_date` date DEFAULT NULL,
    `adults` int(11) DEFAULT 1,
    `children` int(11) DEFAULT 0,
    `infants` int(11) DEFAULT 0,
    `seniors` int(11) DEFAULT 0,
    `total_travelers` int(11) GENERATED ALWAYS AS (`adults` + `children` + `infants` + `seniors`) STORED,
    `room_type` varchar(100) DEFAULT '',
    `special_requests` text,
    `dietary_requirements` text,
    `accessibility_needs` text,
    `base_price` decimal(10,2) NOT NULL DEFAULT 0.00,
    `discount_amount` decimal(10,2) DEFAULT 0.00,
    `tax_amount` decimal(10,2) DEFAULT 0.00,
    `service_fee` decimal(10,2) DEFAULT 0.00,
    `total_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
    `currency` varchar(3) DEFAULT 'USD',
    `payment_status` enum('Pending','Partial','Paid','Refunded','Cancelled') DEFAULT 'Pending',
    `booking_status` enum('Pending','Confirmed','Cancelled','Completed','No Show') DEFAULT 'Pending',
    `confirmation_status` enum('Unconfirmed','Confirmed','Auto-Confirmed') DEFAULT 'Unconfirmed',
    `cancellation_reason` text,
    `cancellation_fee` decimal(10,2) DEFAULT 0.00,
    `refund_amount` decimal(10,2) DEFAULT 0.00,
    `source` enum('Website','Phone','Email','Agent','Mobile App') DEFAULT 'Website',
    `agent_id` int(11) unsigned DEFAULT 0,
    `promo_code` varchar(50) DEFAULT '',
    `promo_discount` decimal(10,2) DEFAULT 0.00,
    `booking_notes` text,
    `internal_notes` text,
    `reminder_sent` tinyint(1) DEFAULT 0,
    `feedback_requested` tinyint(1) DEFAULT 0,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `confirmed_at` datetime DEFAULT NULL,
    `cancelled_at` datetime DEFAULT NULL,
    `completed_at` datetime DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_booking_reference` (`booking_reference`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_package_id` (`package_id`),
    KEY `idx_departure_date` (`departure_date`),
    KEY `idx_booking_status` (`booking_status`),
    KEY `idx_payment_status` (`payment_status`),
    KEY `idx_created` (`created`),
    FOREIGN KEY (`customer_id`) REFERENCES `#__hp_customers` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`package_id`) REFERENCES `#__hp_packages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Booking Travelers Table (for storing individual traveler details)
CREATE TABLE IF NOT EXISTS `#__hp_booking_travelers` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `booking_id` int(11) unsigned NOT NULL,
    `traveler_type` enum('Adult','Child','Infant','Senior') NOT NULL,
    `first_name` varchar(100) NOT NULL,
    `last_name` varchar(100) NOT NULL,
    `date_of_birth` date DEFAULT NULL,
    `gender` enum('Male','Female','Other') DEFAULT NULL,
    `passport_number` varchar(50) DEFAULT '',
    `passport_expiry` date DEFAULT NULL,
    `nationality` varchar(100) DEFAULT '',
    `dietary_requirements` text,
    `medical_conditions` text,
    `room_preference` varchar(100) DEFAULT '',
    `seat_preference` varchar(100) DEFAULT '',
    `travel_insurance` tinyint(1) DEFAULT 0,
    `emergency_contact_name` varchar(255) DEFAULT '',
    `emergency_contact_phone` varchar(20) DEFAULT '',
    `special_assistance` text,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_booking_id` (`booking_id`),
    KEY `idx_traveler_type` (`traveler_type`),
    FOREIGN KEY (`booking_id`) REFERENCES `#__hp_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Payments Table
CREATE TABLE IF NOT EXISTS `#__hp_payments` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `booking_id` int(11) unsigned NOT NULL,
    `payment_reference` varchar(50) NOT NULL,
    `gateway` enum('PayPal','Stripe','Razorpay','Square','Bank Transfer','Cash','Cheque') NOT NULL,
    `transaction_id` varchar(255) DEFAULT '',
    `payment_method` varchar(100) DEFAULT '',
    `payment_type` enum('Full Payment','Partial Payment','Deposit','Refund') DEFAULT 'Full Payment',
    `amount` decimal(10,2) NOT NULL DEFAULT 0.00,
    `currency` varchar(3) DEFAULT 'USD',
    `gateway_fee` decimal(10,2) DEFAULT 0.00,
    `net_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
    `status` enum('Pending','Processing','Completed','Failed','Cancelled','Refunded') DEFAULT 'Pending',
    `gateway_response` longtext,
    `failure_reason` text,
    `payment_date` datetime DEFAULT NULL,
    `refund_date` datetime DEFAULT NULL,
    `refund_reference` varchar(255) DEFAULT '',
    `notes` text,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_payment_reference` (`payment_reference`),
    KEY `idx_booking_id` (`booking_id`),
    KEY `idx_gateway` (`gateway`),
    KEY `idx_status` (`status`),
    KEY `idx_payment_date` (`payment_date`),
    FOREIGN KEY (`booking_id`) REFERENCES `#__hp_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Reviews and Ratings Table
CREATE TABLE IF NOT EXISTS `#__hp_reviews` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `package_id` int(11) unsigned NOT NULL,
    `customer_id` int(11) unsigned NOT NULL,
    `booking_id` int(11) unsigned DEFAULT NULL,
    `title` varchar(255) NOT NULL DEFAULT '',
    `review_text` longtext NOT NULL,
    `rating_overall` decimal(2,1) DEFAULT 0.0,
    `rating_value_money` decimal(2,1) DEFAULT 0.0,
    `rating_service` decimal(2,1) DEFAULT 0.0,
    `rating_cleanliness` decimal(2,1) DEFAULT 0.0,
    `rating_location` decimal(2,1) DEFAULT 0.0,
    `rating_facilities` decimal(2,1) DEFAULT 0.0,
    `rating_food` decimal(2,1) DEFAULT 0.0,
    `helpful_votes` int(11) DEFAULT 0,
    `unhelpful_votes` int(11) DEFAULT 0,
    `travel_date` date DEFAULT NULL,
    `traveler_type` enum('Solo','Couple','Family','Friends','Business') DEFAULT NULL,
    `verified_booking` tinyint(1) DEFAULT 0,
    `pros` text,
    `cons` text,
    `tips` text,
    `images` text,
    `status` enum('Pending','Approved','Rejected','Spam') DEFAULT 'Pending',
    `admin_response` text,
    `responded_at` datetime DEFAULT NULL,
    `responded_by` int(11) unsigned DEFAULT 0,
    `featured` tinyint(1) DEFAULT 0,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `published` tinyint(1) DEFAULT 1,
    PRIMARY KEY (`id`),
    KEY `idx_package_id` (`package_id`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_booking_id` (`booking_id`),
    KEY `idx_status` (`status`),
    KEY `idx_rating_overall` (`rating_overall`),
    KEY `idx_verified_booking` (`verified_booking`),
    KEY `idx_featured` (`featured`),
    KEY `idx_created` (`created`),
    FOREIGN KEY (`package_id`) REFERENCES `#__hp_packages` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`customer_id`) REFERENCES `#__hp_customers` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`booking_id`) REFERENCES `#__hp_bookings` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Offers and Promotions Table
CREATE TABLE IF NOT EXISTS `#__hp_offers` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL DEFAULT '',
    `code` varchar(50) NOT NULL DEFAULT '',
    `description` text,
    `terms_conditions` text,
    `offer_type` enum('Percentage','Fixed Amount','Free Service','BOGO') DEFAULT 'Percentage',
    `discount_value` decimal(10,2) NOT NULL DEFAULT 0.00,
    `minimum_amount` decimal(10,2) DEFAULT 0.00,
    `maximum_discount` decimal(10,2) DEFAULT 0.00,
    `applicable_packages` text,
    `applicable_destinations` text,
    `applicable_categories` text,
    `user_limit_per_code` int(11) DEFAULT 1,
    `total_usage_limit` int(11) DEFAULT 0,
    `current_usage` int(11) DEFAULT 0,
    `user_type` enum('All','New','Existing','VIP') DEFAULT 'All',
    `booking_window_start` datetime DEFAULT NULL,
    `booking_window_end` datetime DEFAULT NULL,
    `travel_period_start` date DEFAULT NULL,
    `travel_period_end` date DEFAULT NULL,
    `advance_booking_days` int(11) DEFAULT 0,
    `combinable_with_other_offers` tinyint(1) DEFAULT 0,
    `auto_apply` tinyint(1) DEFAULT 0,
    `priority` int(11) DEFAULT 0,
    `featured` tinyint(1) DEFAULT 0,
    `published` tinyint(1) DEFAULT 1,
    `created_by` int(11) unsigned DEFAULT 0,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified_by` int(11) unsigned DEFAULT 0,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_code` (`code`),
    KEY `idx_offer_type` (`offer_type`),
    KEY `idx_published` (`published`),
    KEY `idx_featured` (`featured`),
    KEY `idx_booking_window` (`booking_window_start`, `booking_window_end`),
    KEY `idx_travel_period` (`travel_period_start`, `travel_period_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Offer Usage Tracking
CREATE TABLE IF NOT EXISTS `#__hp_offer_usage` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `offer_id` int(11) unsigned NOT NULL,
    `customer_id` int(11) unsigned NOT NULL,
    `booking_id` int(11) unsigned NOT NULL,
    `discount_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
    `used_at` datetime DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_offer_id` (`offer_id`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_booking_id` (`booking_id`),
    FOREIGN KEY (`offer_id`) REFERENCES `#__hp_offers` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`customer_id`) REFERENCES `#__hp_customers` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`booking_id`) REFERENCES `#__hp_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inquiries Table
CREATE TABLE IF NOT EXISTS `#__hp_inquiries` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `inquiry_type` enum('Package Inquiry','Custom Package','General','Complaint','Feedback','Support') DEFAULT 'Package Inquiry',
    `package_id` int(11) unsigned DEFAULT NULL,
    `customer_id` int(11) unsigned DEFAULT NULL,
    `name` varchar(255) NOT NULL,
    `email` varchar(255) NOT NULL,
    `phone` varchar(20) DEFAULT '',
    `subject` varchar(255) NOT NULL DEFAULT '',
    `message` longtext NOT NULL,
    `travel_date` date DEFAULT NULL,
    `number_of_travelers` int(11) DEFAULT 0,
    `budget_range` varchar(100) DEFAULT '',
    `preferred_destinations` text,
    `special_requirements` text,
    `source` enum('Website','Phone','Email','Chat','Social Media') DEFAULT 'Website',
    `status` enum('New','In Progress','Responded','Closed','Spam') DEFAULT 'New',
    `priority` enum('Low','Medium','High','Urgent') DEFAULT 'Medium',
    `assigned_to` int(11) unsigned DEFAULT 0,
    `admin_notes` text,
    `response` longtext,
    `responded_at` datetime DEFAULT NULL,
    `responded_by` int(11) unsigned DEFAULT 0,
    `follow_up_date` datetime DEFAULT NULL,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_package_id` (`package_id`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_status` (`status`),
    KEY `idx_priority` (`priority`),
    KEY `idx_assigned_to` (`assigned_to`),
    KEY `idx_created` (`created`),
    FOREIGN KEY (`package_id`) REFERENCES `#__hp_packages` (`id`) ON DELETE SET NULL,
    FOREIGN KEY (`customer_id`) REFERENCES `#__hp_customers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Wishlist Table
CREATE TABLE IF NOT EXISTS `#__hp_wishlist` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `customer_id` int(11) unsigned NOT NULL,
    `package_id` int(11) unsigned NOT NULL,
    `notes` text,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_customer_package` (`customer_id`, `package_id`),
    KEY `idx_customer_id` (`customer_id`),
    KEY `idx_package_id` (`package_id`),
    FOREIGN KEY (`customer_id`) REFERENCES `#__hp_customers` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`package_id`) REFERENCES `#__hp_packages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Email Templates Table
CREATE TABLE IF NOT EXISTS `#__hp_email_templates` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `template_key` varchar(100) NOT NULL,
    `name` varchar(255) NOT NULL,
    `subject` varchar(255) NOT NULL DEFAULT '',
    `body_html` longtext,
    `body_text` longtext,
    `variables` text,
    `description` text,
    `category` enum('Booking','Payment','Marketing','Support','System') DEFAULT 'Booking',
    `active` tinyint(1) DEFAULT 1,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_template_key` (`template_key`),
    KEY `idx_category` (`category`),
    KEY `idx_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- System Settings Table
CREATE TABLE IF NOT EXISTS `#__hp_settings` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `setting_key` varchar(100) NOT NULL,
    `setting_value` longtext,
    `setting_type` enum('text','textarea','select','checkbox','radio','json') DEFAULT 'text',
    `category` varchar(50) DEFAULT 'General',
    `description` text,
    `ordering` int(11) DEFAULT 0,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_setting_key` (`setting_key`),
    KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert Default Settings
INSERT INTO `#__hp_settings` (`setting_key`, `setting_value`, `setting_type`, `category`, `description`) VALUES
('company_name', 'Holiday Packages Travel', 'text', 'General', 'Company Name'),
('company_email', 'info@holidaypackages.com', 'text', 'General', 'Company Email'),
('company_phone', '+1-800-HOLIDAY', 'text', 'General', 'Company Phone'),
('default_currency', 'USD', 'text', 'General', 'Default Currency'),
('booking_confirmation_auto', '1', 'checkbox', 'Booking', 'Auto-confirm bookings'),
('booking_reference_prefix', 'HP', 'text', 'Booking', 'Booking Reference Prefix'),
('payment_gateway_default', 'stripe', 'select', 'Payment', 'Default Payment Gateway'),
('email_notifications', '1', 'checkbox', 'Email', 'Enable Email Notifications'),
('sms_notifications', '0', 'checkbox', 'SMS', 'Enable SMS Notifications'),
('review_auto_approve', '0', 'checkbox', 'Reviews', 'Auto-approve reviews'),
('google_maps_api_key', '', 'text', 'Integration', 'Google Maps API Key'),
('paypal_client_id', '', 'text', 'Payment', 'PayPal Client ID'),
('stripe_publishable_key', '', 'text', 'Payment', 'Stripe Publishable Key'),
('razorpay_key_id', '', 'text', 'Payment', 'Razorpay Key ID');

-- Insert Default Email Templates
INSERT INTO `#__hp_email_templates` (`template_key`, `name`, `subject`, `body_html`, `category`) VALUES
('booking_confirmation', 'Booking Confirmation', 'Your Booking Confirmation - {booking_reference}', 
'<h2>Booking Confirmation</h2><p>Dear {customer_name},</p><p>Your booking has been confirmed!</p><p><strong>Booking Reference:</strong> {booking_reference}<br><strong>Package:</strong> {package_title}<br><strong>Departure Date:</strong> {departure_date}<br><strong>Total Amount:</strong> {total_amount}</p>', 'Booking'),
('payment_confirmation', 'Payment Confirmation', 'Payment Received - {booking_reference}', 
'<h2>Payment Confirmation</h2><p>Dear {customer_name},</p><p>We have received your payment.</p><p><strong>Amount:</strong> {payment_amount}<br><strong>Transaction ID:</strong> {transaction_id}</p>', 'Payment'),
('booking_reminder', 'Booking Reminder', 'Your Trip is Coming Up - {package_title}', 
'<h2>Travel Reminder</h2><p>Dear {customer_name},</p><p>Your exciting trip is just around the corner!</p><p><strong>Departure Date:</strong> {departure_date}<br><strong>Package:</strong> {package_title}</p>', 'Booking');

-- Insert Default Categories
INSERT INTO `#__hp_categories` (`title`, `alias`, `description`, `icon_class`, `color`) VALUES
('Adventure Travel', 'adventure-travel', 'Exciting adventure packages for thrill seekers', 'fas fa-mountain', '#e74c3c'),
('Beach Holidays', 'beach-holidays', 'Relaxing beach and coastal destinations', 'fas fa-umbrella-beach', '#3498db'),
('Cultural Tours', 'cultural-tours', 'Explore rich cultural heritage and traditions', 'fas fa-monument', '#f39c12'),
('Family Packages', 'family-packages', 'Perfect packages for family vacations', 'fas fa-users', '#2ecc71'),
('Romantic Getaways', 'romantic-getaways', 'Romantic packages for couples', 'fas fa-heart', '#e91e63'),
('Wildlife Safari', 'wildlife-safari', 'Wildlife and nature exploration tours', 'fas fa-paw', '#27ae60'),
('City Breaks', 'city-breaks', 'Short city break packages', 'fas fa-city', '#9b59b6'),
('Luxury Travel', 'luxury-travel', 'Premium and luxury travel experiences', 'fas fa-gem', '#f1c40f');

-- Create indexes for better performance
CREATE INDEX idx_hp_packages_search ON `#__hp_packages` (`title`, `short_description`, `description`(100));
CREATE INDEX idx_hp_bookings_dates ON `#__hp_bookings` (`departure_date`, `return_date`);
CREATE INDEX idx_hp_payments_gateway_status ON `#__hp_payments` (`gateway`, `status`);
CREATE INDEX idx_hp_reviews_ratings ON `#__hp_reviews` (`rating_overall`, `status`, `published`);